export enum EcomAction{
    GET_BEST_SELLINGS_PHONE='GET_BEST_SELLINGS_PHONE',
    BEST_SELLINGS_LOADING='BEST_SELLINGS_LOADING',
    BEST_SELLINGS_LOADED='BEST_SELLINGS_LOADED',
    BEST_SELLINGS_LOADING_ERROR='BEST_SELLINGS_LOADING_ERROR'
}